/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.keys


import br.com.wdc.shopping.persistence.scheme.tables.EnProduct
import br.com.wdc.shopping.persistence.scheme.tables.EnPurchase
import br.com.wdc.shopping.persistence.scheme.tables.EnPurchaseitem
import br.com.wdc.shopping.persistence.scheme.tables.EnUser
import br.com.wdc.shopping.persistence.scheme.tables.EnUserIntentSecret
import br.com.wdc.shopping.persistence.scheme.tables.EnUserSession

import org.jooq.Record
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val PK_PRODUCT: UniqueKey<Record> = Internal.createUniqueKey(EnProduct.EN_PRODUCT, DSL.name("PK_PRODUCT"), arrayOf(EnProduct.EN_PRODUCT.ID), true)
val PK_PURCHASE: UniqueKey<Record> = Internal.createUniqueKey(EnPurchase.EN_PURCHASE, DSL.name("PK_PURCHASE"), arrayOf(EnPurchase.EN_PURCHASE.ID), true)
val PK_PURCHASEITEM: UniqueKey<Record> = Internal.createUniqueKey(EnPurchaseitem.EN_PURCHASEITEM, DSL.name("PK_PURCHASEITEM"), arrayOf(EnPurchaseitem.EN_PURCHASEITEM.ID), true)
val PK_USER: UniqueKey<Record> = Internal.createUniqueKey(EnUser.EN_USER, DSL.name("PK_USER"), arrayOf(EnUser.EN_USER.ID), true)
val PK_USER_INTENT_SECRET: UniqueKey<Record> = Internal.createUniqueKey(EnUserIntentSecret.EN_USER_INTENT_SECRET, DSL.name("PK_USER_INTENT_SECRET"), arrayOf(EnUserIntentSecret.EN_USER_INTENT_SECRET.USERID), true)
val PK_USER_SESSION: UniqueKey<Record> = Internal.createUniqueKey(EnUserSession.EN_USER_SESSION, DSL.name("PK_USER_SESSION"), arrayOf(EnUserSession.EN_USER_SESSION.SESSION_ID), true)
val UQ_US_REFRESH: UniqueKey<Record> = Internal.createUniqueKey(EnUserSession.EN_USER_SESSION, DSL.name("UQ_US_REFRESH"), arrayOf(EnUserSession.EN_USER_SESSION.REFRESH_TOKEN), true)
