/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.tables


import br.com.wdc.shopping.persistence.scheme.Public
import br.com.wdc.shopping.persistence.scheme.keys.PK_PURCHASE

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


@Suppress("UNCHECKED_CAST")
open class EnPurchase(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        val EN_PURCHASE: EnPurchase = EnPurchase()
    }

    override fun getRecordType(): Class<Record> = Record::class.java

    val ID: TableField<Record, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "")

    val USERID: TableField<Record, Long?> = createField(DSL.name("USERID"), SQLDataType.BIGINT.nullable(false), this, "")

    val BUYDATE: TableField<Record, LocalDateTime?> = createField(DSL.name("BUYDATE"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    constructor(alias: String): this(DSL.name(alias))

    constructor(alias: Name): this(alias, null)

    constructor(): this(DSL.name("EN_PURCHASE"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<Record> = PK_PURCHASE
    override fun `as`(alias: String): EnPurchase = EnPurchase(DSL.name(alias), this)
    override fun `as`(alias: Name): EnPurchase = EnPurchase(alias, this)
    override fun `as`(alias: Table<*>): EnPurchase = EnPurchase(alias.qualifiedName, this)

    override fun rename(name: String): EnPurchase = EnPurchase(DSL.name(name), null)

    override fun rename(name: Name): EnPurchase = EnPurchase(name, null)

    override fun rename(name: Table<*>): EnPurchase = EnPurchase(name.qualifiedName, null)

    override fun where(condition: Condition?): EnPurchase = EnPurchase(qualifiedName, if (aliased()) this else null, condition)

    override fun where(conditions: Collection<Condition>): EnPurchase = where(DSL.and(conditions))

    override fun where(vararg conditions: Condition?): EnPurchase = where(DSL.and(*conditions))

    override fun where(condition: Field<Boolean?>?): EnPurchase = where(DSL.condition(condition))

    @PlainSQL override fun where(condition: SQL): EnPurchase = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String): EnPurchase = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): EnPurchase = where(DSL.condition(condition, *binds))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): EnPurchase = where(DSL.condition(condition, *parts))

    override fun whereExists(select: Select<*>): EnPurchase = where(DSL.exists(select))

    override fun whereNotExists(select: Select<*>): EnPurchase = where(DSL.notExists(select))
}
