/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.tables


import br.com.wdc.shopping.persistence.scheme.Public
import br.com.wdc.shopping.persistence.scheme.keys.PK_USER_INTENT_SECRET

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


@Suppress("UNCHECKED_CAST")
open class EnUserIntentSecret(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        val EN_USER_INTENT_SECRET: EnUserIntentSecret = EnUserIntentSecret()
    }

    override fun getRecordType(): Class<Record> = Record::class.java

    val USERID: TableField<Record, Long?> = createField(DSL.name("USERID"), SQLDataType.BIGINT.nullable(false), this, "")

    val SECRET: TableField<Record, String?> = createField(DSL.name("SECRET"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    constructor(alias: String): this(DSL.name(alias))

    constructor(alias: Name): this(alias, null)

    constructor(): this(DSL.name("EN_USER_INTENT_SECRET"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<Record> = PK_USER_INTENT_SECRET
    override fun `as`(alias: String): EnUserIntentSecret = EnUserIntentSecret(DSL.name(alias), this)
    override fun `as`(alias: Name): EnUserIntentSecret = EnUserIntentSecret(alias, this)
    override fun `as`(alias: Table<*>): EnUserIntentSecret = EnUserIntentSecret(alias.qualifiedName, this)

    override fun rename(name: String): EnUserIntentSecret = EnUserIntentSecret(DSL.name(name), null)

    override fun rename(name: Name): EnUserIntentSecret = EnUserIntentSecret(name, null)

    override fun rename(name: Table<*>): EnUserIntentSecret = EnUserIntentSecret(name.qualifiedName, null)

    override fun where(condition: Condition?): EnUserIntentSecret = EnUserIntentSecret(qualifiedName, if (aliased()) this else null, condition)

    override fun where(conditions: Collection<Condition>): EnUserIntentSecret = where(DSL.and(conditions))

    override fun where(vararg conditions: Condition?): EnUserIntentSecret = where(DSL.and(*conditions))

    override fun where(condition: Field<Boolean?>?): EnUserIntentSecret = where(DSL.condition(condition))

    @PlainSQL override fun where(condition: SQL): EnUserIntentSecret = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String): EnUserIntentSecret = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): EnUserIntentSecret = where(DSL.condition(condition, *binds))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): EnUserIntentSecret = where(DSL.condition(condition, *parts))

    override fun whereExists(select: Select<*>): EnUserIntentSecret = where(DSL.exists(select))

    override fun whereNotExists(select: Select<*>): EnUserIntentSecret = where(DSL.notExists(select))
}
