/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.tables


import br.com.wdc.shopping.persistence.scheme.Public
import br.com.wdc.shopping.persistence.scheme.keys.PK_USER

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


@Suppress("UNCHECKED_CAST")
open class EnUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        val EN_USER: EnUser = EnUser()
    }

    override fun getRecordType(): Class<Record> = Record::class.java

    val ID: TableField<Record, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "")

    val USERNAME: TableField<Record, String?> = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    val PASSWORD: TableField<Record, String?> = createField(DSL.name("PASSWORD"), SQLDataType.CHAR(32).nullable(false), this, "")

    val NAME: TableField<Record, String?> = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    val ROLES: TableField<Record, String?> = createField(DSL.name("ROLES"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    constructor(alias: String): this(DSL.name(alias))

    constructor(alias: Name): this(alias, null)

    constructor(): this(DSL.name("EN_USER"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<Record> = PK_USER
    override fun `as`(alias: String): EnUser = EnUser(DSL.name(alias), this)
    override fun `as`(alias: Name): EnUser = EnUser(alias, this)
    override fun `as`(alias: Table<*>): EnUser = EnUser(alias.qualifiedName, this)

    override fun rename(name: String): EnUser = EnUser(DSL.name(name), null)

    override fun rename(name: Name): EnUser = EnUser(name, null)

    override fun rename(name: Table<*>): EnUser = EnUser(name.qualifiedName, null)

    override fun where(condition: Condition?): EnUser = EnUser(qualifiedName, if (aliased()) this else null, condition)

    override fun where(conditions: Collection<Condition>): EnUser = where(DSL.and(conditions))

    override fun where(vararg conditions: Condition?): EnUser = where(DSL.and(*conditions))

    override fun where(condition: Field<Boolean?>?): EnUser = where(DSL.condition(condition))

    @PlainSQL override fun where(condition: SQL): EnUser = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String): EnUser = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): EnUser = where(DSL.condition(condition, *binds))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): EnUser = where(DSL.condition(condition, *parts))

    override fun whereExists(select: Select<*>): EnUser = where(DSL.exists(select))

    override fun whereNotExists(select: Select<*>): EnUser = where(DSL.notExists(select))
}
