/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.tables


import br.com.wdc.shopping.persistence.scheme.Public
import br.com.wdc.shopping.persistence.scheme.keys.PK_USER_SESSION
import br.com.wdc.shopping.persistence.scheme.keys.UQ_US_REFRESH

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


@Suppress("UNCHECKED_CAST")
open class EnUserSession(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Record>?,
    parentPath: InverseForeignKey<out Record, Record>?,
    aliased: Table<Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        val EN_USER_SESSION: EnUserSession = EnUserSession()
    }

    override fun getRecordType(): Class<Record> = Record::class.java

    val SESSION_ID: TableField<Record, String?> = createField(DSL.name("SESSION_ID"), SQLDataType.VARCHAR(36).nullable(false), this, "")

    val USERID: TableField<Record, Long?> = createField(DSL.name("USERID"), SQLDataType.BIGINT.nullable(false), this, "")

    val USERNAME: TableField<Record, String?> = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    val REFRESH_TOKEN: TableField<Record, String?> = createField(DSL.name("REFRESH_TOKEN"), SQLDataType.VARCHAR(36).nullable(false), this, "")

    val EXPIRES_AT: TableField<Record, LocalDateTime?> = createField(DSL.name("EXPIRES_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    val PERMISSIONS: TableField<Record, String?> = createField(DSL.name("PERMISSIONS"), SQLDataType.VARCHAR(4000), this, "")

    val RSA_PUBLIC_KEY: TableField<Record, String?> = createField(DSL.name("RSA_PUBLIC_KEY"), SQLDataType.VARCHAR(2000).nullable(false), this, "")

    val RSA_PRIVATE_KEY: TableField<Record, String?> = createField(DSL.name("RSA_PRIVATE_KEY"), SQLDataType.VARCHAR(4000).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    constructor(alias: String): this(DSL.name(alias))

    constructor(alias: Name): this(alias, null)

    constructor(): this(DSL.name("EN_USER_SESSION"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<Record> = PK_USER_SESSION
    override fun getUniqueKeys(): List<UniqueKey<Record>> = listOf(UQ_US_REFRESH)
    override fun `as`(alias: String): EnUserSession = EnUserSession(DSL.name(alias), this)
    override fun `as`(alias: Name): EnUserSession = EnUserSession(alias, this)
    override fun `as`(alias: Table<*>): EnUserSession = EnUserSession(alias.qualifiedName, this)

    override fun rename(name: String): EnUserSession = EnUserSession(DSL.name(name), null)

    override fun rename(name: Name): EnUserSession = EnUserSession(name, null)

    override fun rename(name: Table<*>): EnUserSession = EnUserSession(name.qualifiedName, null)

    override fun where(condition: Condition?): EnUserSession = EnUserSession(qualifiedName, if (aliased()) this else null, condition)

    override fun where(conditions: Collection<Condition>): EnUserSession = where(DSL.and(conditions))

    override fun where(vararg conditions: Condition?): EnUserSession = where(DSL.and(*conditions))

    override fun where(condition: Field<Boolean?>?): EnUserSession = where(DSL.condition(condition))

    @PlainSQL override fun where(condition: SQL): EnUserSession = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String): EnUserSession = where(DSL.condition(condition))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): EnUserSession = where(DSL.condition(condition, *binds))

    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): EnUserSession = where(DSL.condition(condition, *parts))

    override fun whereExists(select: Select<*>): EnUserSession = where(DSL.exists(select))

    override fun whereNotExists(select: Select<*>): EnUserSession = where(DSL.notExists(select))
}
