/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme


import kotlin.collections.List

import org.jooq.Constants
import org.jooq.Schema
import org.jooq.impl.CatalogImpl


@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    val PUBLIC: Public get(): Public = Public.PUBLIC

    override fun getSchemas(): List<Schema> = listOf(
        Public.PUBLIC
    )

    private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_19
}
