/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme


import br.com.wdc.shopping.persistence.scheme.sequences.SQ_PRODUCT
import br.com.wdc.shopping.persistence.scheme.sequences.SQ_PURCHASE
import br.com.wdc.shopping.persistence.scheme.sequences.SQ_PURCHASEITEM
import br.com.wdc.shopping.persistence.scheme.sequences.SQ_USER
import br.com.wdc.shopping.persistence.scheme.tables.EnProduct
import br.com.wdc.shopping.persistence.scheme.tables.EnPurchase
import br.com.wdc.shopping.persistence.scheme.tables.EnPurchaseitem
import br.com.wdc.shopping.persistence.scheme.tables.EnUser
import br.com.wdc.shopping.persistence.scheme.tables.EnUserIntentSecret
import br.com.wdc.shopping.persistence.scheme.tables.EnUserSession

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("PUBLIC", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        val PUBLIC: Public = Public()
    }

    val EN_PRODUCT: EnProduct get() = EnProduct.EN_PRODUCT

    val EN_PURCHASE: EnPurchase get() = EnPurchase.EN_PURCHASE

    val EN_PURCHASEITEM: EnPurchaseitem get() = EnPurchaseitem.EN_PURCHASEITEM

    val EN_USER: EnUser get() = EnUser.EN_USER

    val EN_USER_INTENT_SECRET: EnUserIntentSecret get() = EnUserIntentSecret.EN_USER_INTENT_SECRET

    val EN_USER_SESSION: EnUserSession get() = EnUserSession.EN_USER_SESSION

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        SQ_PRODUCT,
        SQ_PURCHASE,
        SQ_PURCHASEITEM,
        SQ_USER
    )

    override fun getTables(): List<Table<*>> = listOf(
        EnProduct.EN_PRODUCT,
        EnPurchase.EN_PURCHASE,
        EnPurchaseitem.EN_PURCHASEITEM,
        EnUser.EN_USER,
        EnUserIntentSecret.EN_USER_INTENT_SECRET,
        EnUserSession.EN_USER_SESSION
    )
}
