/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.sequences


import br.com.wdc.shopping.persistence.scheme.Public

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



val SQ_PRODUCT: Sequence<Long> = Internal.createSequence("SQ_PRODUCT", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null)

val SQ_PURCHASE: Sequence<Long> = Internal.createSequence("SQ_PURCHASE", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null)

val SQ_PURCHASEITEM: Sequence<Long> = Internal.createSequence("SQ_PURCHASEITEM", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null)

val SQ_USER: Sequence<Long> = Internal.createSequence("SQ_USER", Public.PUBLIC, SQLDataType.BIGINT, null, null, null, null, false, null)
