/*
 * This file is generated by jOOQ.
 */
package br.com.wdc.shopping.persistence.scheme.tables.references


import br.com.wdc.shopping.persistence.scheme.tables.EnProduct
import br.com.wdc.shopping.persistence.scheme.tables.EnPurchase
import br.com.wdc.shopping.persistence.scheme.tables.EnPurchaseitem
import br.com.wdc.shopping.persistence.scheme.tables.EnUser
import br.com.wdc.shopping.persistence.scheme.tables.EnUserIntentSecret
import br.com.wdc.shopping.persistence.scheme.tables.EnUserSession



val EN_PRODUCT: EnProduct = EnProduct.EN_PRODUCT

val EN_PURCHASE: EnPurchase = EnPurchase.EN_PURCHASE

val EN_PURCHASEITEM: EnPurchaseitem = EnPurchaseitem.EN_PURCHASEITEM

val EN_USER: EnUser = EnUser.EN_USER

val EN_USER_INTENT_SECRET: EnUserIntentSecret = EnUserIntentSecret.EN_USER_INTENT_SECRET

val EN_USER_SESSION: EnUserSession = EnUserSession.EN_USER_SESSION
