-- Esquema do banco H2 tal como existia antes da adoção do jOOQ (Fase 4 da migração de persistência),
-- extraído de um banco real com SCRIPT NODATA. Serve de ponto de partida para o teste das migrações.

CREATE SEQUENCE "PUBLIC"."SQ_MIGRATION_LOG" START WITH 1;

CREATE SEQUENCE "PUBLIC"."SQ_PRODUCT" START WITH 1;

CREATE SEQUENCE "PUBLIC"."SQ_PURCHASE" START WITH 1;

CREATE SEQUENCE "PUBLIC"."SQ_PURCHASEITEM" START WITH 1;

CREATE SEQUENCE "PUBLIC"."SQ_USER" START WITH 1;

CREATE TABLE "PUBLIC"."EN_MIGRATION_LOG"(
    "ID" BIGINT NOT NULL,
    "SCRIPT_NAME" CHARACTER VARYING(255) NOT NULL,
    "STEP_NAME" CHARACTER VARYING(255) NOT NULL,
    "EXECUTED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "PUBLIC"."EN_MIGRATION_LOG" ADD CONSTRAINT "PUBLIC"."PK_MIGRATION_LOG" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."EN_USER"(
    "ID" BIGINT NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL,
    "PASSWORD" CHARACTER(32) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "ROLES" CHARACTER VARYING(255)
);

ALTER TABLE "PUBLIC"."EN_USER" ADD CONSTRAINT "PUBLIC"."PK_USER" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."EN_PRODUCT"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR_IGNORECASE(1000000) NOT NULL,
    "PRICE" NUMERIC(20, 2) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(1000000) NOT NULL,
    "IMAGE" BINARY(1000000)
);

ALTER TABLE "PUBLIC"."EN_PRODUCT" ADD CONSTRAINT "PUBLIC"."PK_PRODUCT" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."EN_PURCHASE"(
    "ID" BIGINT NOT NULL,
    "USERID" BIGINT NOT NULL,
    "BUYDATE" TIMESTAMP NOT NULL
);

ALTER TABLE "PUBLIC"."EN_PURCHASE" ADD CONSTRAINT "PUBLIC"."PK_PURCHASE" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."EN_PURCHASEITEM"(
    "ID" BIGINT NOT NULL,
    "PURCHASEID" BIGINT NOT NULL,
    "PRODUCTID" BIGINT NOT NULL,
    "AMOUNT" INTEGER NOT NULL,
    "PRICE" NUMERIC(20, 2) NOT NULL
);

ALTER TABLE "PUBLIC"."EN_PURCHASEITEM" ADD CONSTRAINT "PUBLIC"."PK_PURCHASEITEM" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."EN_USER_INTENT_SECRET"(
    "USERID" BIGINT NOT NULL,
    "SECRET" CHARACTER VARYING(64) NOT NULL
);

ALTER TABLE "PUBLIC"."EN_USER_INTENT_SECRET" ADD CONSTRAINT "PUBLIC"."PK_USER_INTENT_SECRET" PRIMARY KEY("USERID");

CREATE TABLE "PUBLIC"."EN_USER_SESSION"(
    "SESSION_ID" CHARACTER VARYING(36) NOT NULL,
    "USERID" BIGINT NOT NULL,
    "USERNAME" CHARACTER VARYING(100) NOT NULL,
    "REFRESH_TOKEN" CHARACTER VARYING(36) NOT NULL,
    "EXPIRES_AT" TIMESTAMP NOT NULL,
    "PERMISSIONS" CHARACTER VARYING(4000),
    "RSA_PUBLIC_KEY" CHARACTER VARYING(2000) NOT NULL,
    "RSA_PRIVATE_KEY" CHARACTER VARYING(4000) NOT NULL
);

ALTER TABLE "PUBLIC"."EN_USER_SESSION" ADD CONSTRAINT "PUBLIC"."PK_USER_SESSION" PRIMARY KEY("SESSION_ID");

ALTER TABLE "PUBLIC"."EN_USER_SESSION" ADD CONSTRAINT "PUBLIC"."UQ_US_REFRESH" UNIQUE NULLS DISTINCT ("REFRESH_TOKEN");

ALTER TABLE "PUBLIC"."EN_PURCHASEITEM" ADD CONSTRAINT "PUBLIC"."FK_PURCHASEITEM_PURCHASE" FOREIGN KEY("PURCHASEID") REFERENCES "PUBLIC"."EN_PURCHASE"("ID");

ALTER TABLE "PUBLIC"."EN_USER_INTENT_SECRET" ADD CONSTRAINT "PUBLIC"."FK_UIS_USER" FOREIGN KEY("USERID") REFERENCES "PUBLIC"."EN_USER"("ID");

ALTER TABLE "PUBLIC"."EN_USER_SESSION" ADD CONSTRAINT "PUBLIC"."FK_US_USER" FOREIGN KEY("USERID") REFERENCES "PUBLIC"."EN_USER"("ID");

ALTER TABLE "PUBLIC"."EN_PURCHASEITEM" ADD CONSTRAINT "PUBLIC"."FK_PURCHASEITEM_PRODUCT" FOREIGN KEY("PRODUCTID") REFERENCES "PUBLIC"."EN_PRODUCT"("ID");

ALTER TABLE "PUBLIC"."EN_PURCHASE" ADD CONSTRAINT "PUBLIC"."FK_PURCHASE_USER" FOREIGN KEY("USERID") REFERENCES "PUBLIC"."EN_USER"("ID");
